# Generated by Django 5.2.3 on 2025-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_api_base', models.URLField(default='https://server.com/api', help_text='LLM API基础URL')),
                ('llm_api_key', models.CharField(default='', help_text='LLM API密钥', max_length=200)),
                ('llm_model', models.CharField(default='', help_text='LLM模型名称', max_length=100)),
                ('web_host', models.CharField(default='0.0.0.0', help_text='Web服务器监听地址', max_length=100)),
                ('web_http_port', models.IntegerField(default=8000, help_text='HTTP端口')),
                ('web_https_port', models.IntegerField(default=8443, help_text='HTTPS端口')),
                ('web_ssl_enabled', models.BooleanField(default=False, help_text='启用HTTPS/SSL')),
                ('web_ssl_cert_file', models.FileField(blank=True, help_text='上传SSL证书文件(.crt或.pem)', null=True, upload_to='ssl_certs/')),
                ('web_ssl_key_file', models.FileField(blank=True, help_text='上传SSL私钥文件(.key)', null=True, upload_to='ssl_certs/')),
                ('funasr_host', models.CharField(default='funasr', help_text='FunASR服务器地址', max_length=100)),
                ('funasr_port', models.IntegerField(default=10095, help_text='FunASR服务器端口')),
                ('funasr_ssl', models.BooleanField(default=False, help_text='是否使用SSL')),
                ('funasr_ssl_verify', models.BooleanField(default=False, help_text='是否验证SSL证书')),
                ('use_connection_pool', models.BooleanField(default=True, help_text='是否使用连接池模式')),
                ('pool_min_connections', models.IntegerField(default=2, help_text='连接池最小连接数')),
                ('pool_max_connections', models.IntegerField(default=20, help_text='连接池最大连接数')),
                ('pool_max_idle_time', models.IntegerField(default=300, help_text='连接最大空闲时间（秒）')),
                ('session_cleanup_hours', models.IntegerField(default=1, help_text='清理非活跃用户的小时数')),
                ('max_conversation_history', models.IntegerField(default=5, help_text='最大对话历史轮数')),
                ('audio_sample_rate', models.IntegerField(choices=[(8000, '8kHz'), (16000, '16kHz'), (22050, '22kHz')], default=16000)),
                ('audio_chunk_size', models.IntegerField(default=4096, help_text='音频块大小')),
                ('audio_send_interval', models.IntegerField(default=100, help_text='发送间隔(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='会话ID', max_length=50, unique=True)),
                ('conversation_history', models.JSONField(default=list, help_text='对话历史')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'ordering': ['-last_active'],
            },
        ),
    ]
